dist: bionic
sudo: required
language: java
script:
  - jdk_switcher use oraclejdk8
  - export REPOSITORY_URL=$(git remote -v | awk '{print $2}')
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then ./builder.sh deploy; fi'
  - 'if [ "$TRAVIS_BRANCH" != "master" ]; then ./gradlew build; fi'
