version: '3'
services:
  travis-build:
    image: adoptopenjdk:8u232-b09-jdk-hotspot
    command: ./builder.sh deploy
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root
    environment:
      - CURRENT_BRANCH=$TRAVIS_BRANCH # current branch name
      - REPO_TOKEN=$REPO_TOKEN
      - NEXUS_USERNAME=$NEXUS_USERNAME
      - NEXUS_PASSWORD=$NEXUS_PASSWORD
      - GPG_CIPHER_KEY=$GPG_CIPHER_KEY
      - GPG_KEY_ID=$GPG_KEY_ID

  travis-pull-request-build:
    image: adoptopenjdk:8u232-b09-jdk-hotspot
    command: ./gradlew build
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root
